### ISSUE TITLE
Assertion error while running LIQUORICE

### ISSUE THREAD

**Issue by DucoG** [epigen/LIQUORICE#6]
Hi,

The environment is working and im running it on my samples now (using snakemake). however, for this specific sample i received this error:

```
Traceback (most recent call last):
  File "/home/d.gaillard/miniconda3/envs/LIQUORICE/lib/python3.8/site-packages/liquorice/utils/BinTableBiasFactors.py", line 126, in get_GC_and_di_and_trinuc_weights
    trinuc_res_dict[trinuc]+=trinuc_weight
KeyError: 'TTW'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/d.gaillard/miniconda3/envs/LIQUORICE/lib/python3.8/site-packages/liquorice/utils/BinTableBiasFactors.py", line 129, in get_GC_and_di_and_trinuc_weights
    trinuc_revcomp=self.revcompdict[trinuc]
KeyError: 'TTW'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/d.gaillard/miniconda3/envs/LIQUORICE/bin/LIQUORICE", line 10, in <module> 
    sys.exit(main())
  File "/home/d.gaillard/miniconda3/envs/LIQUORICE/lib/python3.8/site-packages/liquorice/LIQUORICE.py", line 397, in main
    Workflows.train_biasmodel_for_sample(
  File "/home/d.gaillard/miniconda3/envs/LIQUORICE/lib/python3.8/site-packages/liquorice/utils/Workflows.py", line 170, in train_biasmodel_for_sample
    liq_table=add_biasfactors_percentile_split(avg_readlength, liq_table, n_cores, sampled_fragment_lengths)
  File "/home/d.gaillard/miniconda3/envs/LIQUORICE/lib/python3.8/site-packages/liquorice/utils/Workflows.py", line 52, in add_biasfactors_percentile_split
    liq_table_with_biasfactors = BinTableBiasFactors.BiasFactorHandler(
  File "/home/d.gaillard/miniconda3/envs/LIQUORICE/lib/python3.8/site-packages/liquorice/utils/BinTableBiasFactors.py", line 287, in get_table_with_bias_factors
    nuc_and_gc_factors_dicts= self.df["sequence"].apply(
  File "/home/d.gaillard/miniconda3/envs/LIQUORICE/lib/python3.8/site-packages/pandas/core/series.py", line 4212, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "pandas/_libs/lib.pyx", line 2403, in pandas._libs.lib.map_infer
  File "/home/d.gaillard/miniconda3/envs/LIQUORICE/lib/python3.8/site-packages/liquorice/utils/BinTableBiasFactors.py", line 132, in get_GC_and_di_and_trinuc_weights
    assert len(trinuc)<3 or "N" in trinuc  # if at (second-to-) last position or an "N" is contained
AssertionError
```

this is the command i used:
```
LIQUORICE --bamfile /home/d.gaillard/hg38_align/data/aligned_hs38/25871P_WGS_hs38.bam             
--refgenome_fasta /ssd/d.gaillard/new_refs/hs38.fa             
--mappability_bigwig /ssd/d.gaillard/new_refs/hg38.fa.mappability_100bp.bw             
--bedpathlist "/home/d.gaillard/hg38_liquorice/region_beds/housekeeping_genes.bed"             
--bedpath_biasmodel "10k_random"             
--cna_seg_file /home/d.gaillard/hg38_ichorcna/results/ichorCNA/25871P/25871P.seg             
--blacklist /ssd/d.gaillard/new_refs/hg38.blacklist.v2.0.bed --binsize 5000 --extend_to 15000
```

all samples should be the same so I don't really understand what could be happening. Any ideas?

**Comment by DucoG** [comment]
Hi,

After a quick look, I think i figured out the issue:
https://github.com/epigen/LIQUORICE/blame/68fa1b92d6a54f63c44812393cd78fbd0ac0b262/liquorice/utils/BinTableBiasFactors.py#L116

The line above only checks for "N" but not for other IUPAC nucleotide codes which reference multiple possible nucleotides

from https://www.bioinformatics.org/sms/iupac.html
```
IUPAC nucleotide code | Base
-- | --
A | Adenine
C | Cytosine
G | Guanine
T (or U) | Thymine (or Uracil)
R | A or G
Y | C or T
S | G or C
W | A or T
K | G or T
M | A or C
B | C or G or T
D | A or G or T
H | A or C or T
V | A or C or G
N | any base
. or - | gap
```

**proposed changes to solve the issue:**
https://github.com/epigen/LIQUORICE/blame/68fa1b92d6a54f63c44812393cd78fbd0ac0b262/liquorice/utils/BinTableBiasFactors.py#L132
change to
```python
assert len(trinuc)<3 or any(x in trinuc for x in ["N", "R", "Y", "S", "W", "K", "M", "B", "D", "H"]
```


https://github.com/epigen/LIQUORICE/blame/68fa1b92d6a54f63c44812393cd78fbd0ac0b262/liquorice/utils/BinTableBiasFactors.py#L116
change to
```python
assert len(dinuc)<2 or any(x in dinuc for x in ["N", "R", "Y", "S", "W", "K", "M", "B", "D", "H"]
```


https://github.com/epigen/LIQUORICE/blame/68fa1b92d6a54f63c44812393cd78fbd0ac0b262/liquorice/utils/BinTableBiasFactors.py#L94-L99
change to:
```python
if nuc=="G" or nuc=="g" or nuc=="c" or nuc=="C" or nuc=="S" or nuc=="s":
                GC_at_pos=1
            elif nuc=="A" or nuc=="a" or nuc=="t" or nuc=="T" or nuc=="W" or nuc=="w":
                GC_at_pos=0
            elif nuc=="R" or nuc=="r" or nuc=="Y" or nuc=="y" or nuc=="K" or nuc=="k" or nuc=="M" or nuc=="m":
                GC_at_pos=0.5
            elif nuc=="B" or nuc=="b" or nuc=="V" or nuc=="v":
                GC_at_pos=0.667
            elif nuc=="D" or nuc=="d" or nuc=="H" or nuc=="h":
                GC_at_pos=0.333
            elif nuc=="N" or nuc=="n":
                GC_at_pos=0.461 #0.461 is the genome-wide GC content mean
```

With these changes, the code finishes without errors. I cant speak for the validity of the results ofcourse :)


cheers, Duco

**Comment by peneder** [comment]
Hi Duco,

Well done! :D You're changes seem exactly right to me. I'm pretty sure the results should be correct now. 

EDIT: I've just seen that you're using hs38, not hg38. I didn't think of genomes other than hg19/hg38 when building the tool.  I'll include your changes in the next release - thanks for the fix :) 

best
Peter

**Comment by peneder** [comment]
I'll close this for now, feel free to re-open if issues persist!
