### ISSUE TITLE
Error when running LIQUORICE_summary - throws "KeyError: 1"

### ISSUE THREAD

**Issue by danarte** [epigen/LIQUORICE#9]
Hello again,
I'm trying to run the summary tool on the output of several regions of interest for multiple samples.
It appears to run successfully some of the analysis but consistently throwing a "KeyError: 1" error and not finishing the summary.
Here are some of the relevant details:
Here is an example of the "fitted_gaussians_parameter_summary.csv" files for one of the samples:
```
G1_amplitude,G1_sigma,G2_amplitude,G2_sigma,G3_amplitude,G3_sigma,Bayesian Information Criterion,Total dip depth,Intercept,Total dip area (AOC combined model),sample,region-set
-633.0237723176843,149.0000000036123,-228.45001707792173,757.999999030593,-3403.019088864516,6078.096277394091,-103.8125002646686,2.038495151540359,0.05913016518462497,-4315.9248614404005,HD_6.100K,universal_DHSs

```
It looks like all folders have a valid fitted_gaussians_parameter_summary.csv in them.

After running the analysis, the directory contains "summary_across_samples_and_ROIS.csv" file which seems complete, and a bunch of region_of_interest_summary_plot_subplots_of_samples_by_Dip_area.pdf and  region_of_interest_summary_plot_overlay_of_samples_by_Dip_area.pdf 
Compared to a successfull run, the files that are missing are: boxplot_summary_by_dip_depth.pdf and boxplot_summary_by_dip_area.pdf as well as the "...samples_by_Dip_depth.pdf" files for all of the regions.

If you need any more details please let me know.

Here is the output and error of the summary command:
```
(LIQUORICE_python4) [artemd@compute-0-2 liqourice_output]$ LIQUORICE_summary --dirname ./ --control_name_list HD_5.5Mil HD_8.5Mil HD_6.5Mil HD_7.5Mil HD_2.5Mil HD_12.5Mil HD_11.5Mil HD_10.5Mil HD_4.5Mil HD_9.5Mil HD_3.5Mil
/groups/nshomron/artemd/.conda/envs/LIQUORICE_python4/lib/python3.8/site-packages/liquorice/LIQUORICE_summary.py:723: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='area'` for the same effect.
  sns.violinplot(x="Region-set",y=comparison_col,hue="Case/Control",data=summary_df,
/groups/nshomron/artemd/.conda/envs/LIQUORICE_python4/lib/python3.8/site-packages/liquorice/LIQUORICE_summary.py:723: FutureWarning:

The `scale_hue` parameter has been replaced and will be removed in v0.15.0. Pass `common_norm=True` for the same effect.
  sns.violinplot(x="Region-set",y=comparison_col,hue="Case/Control",data=summary_df,
/groups/nshomron/artemd/.local/lib/python3.8/site-packages/seaborn/categorical.py:545: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  dodge_move = offsets[sub_data["hue"].map(self._hue_map.levels.index)]
Traceback (most recent call last):
  File "/groups/nshomron/artemd/.conda/envs/LIQUORICE_python4/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2895, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 96, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 120, in pandas._libs.index.IndexEngine._get_loc_duplicates
KeyError: 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/groups/nshomron/artemd/.conda/envs/LIQUORICE_python4/bin/LIQUORICE_summary", line 10, in <module>
    sys.exit(main())
  File "/groups/nshomron/artemd/.conda/envs/LIQUORICE_python4/lib/python3.8/site-packages/liquorice/LIQUORICE_summary.py", line 879, in main
    boxplot_score_summary(summary_df=summary_df,
  File "/groups/nshomron/artemd/.conda/envs/LIQUORICE_python4/lib/python3.8/site-packages/liquorice/LIQUORICE_summary.py", line 729, in boxplot_score_summary
    sns.swarmplot(x="Region-set",y=comparison_col,hue="Case/Control",data=summary_df,dodge=True,
  File "/groups/nshomron/artemd/.local/lib/python3.8/site-packages/seaborn/categorical.py", line 2249, in swarmplot
    p.plot_swarms(
  File "/groups/nshomron/artemd/.local/lib/python3.8/site-packages/seaborn/categorical.py", line 545, in plot_swarms
    dodge_move = offsets[sub_data["hue"].map(self._hue_map.levels.index)]
  File "/groups/nshomron/artemd/.conda/envs/LIQUORICE_python4/lib/python3.8/site-packages/pandas/core/series.py", line 882, in __getitem__
    return self._get_value(key)
  File "/groups/nshomron/artemd/.conda/envs/LIQUORICE_python4/lib/python3.8/site-packages/pandas/core/series.py", line 989, in _get_value
    loc = self.index.get_loc(label)
  File "/groups/nshomron/artemd/.conda/envs/LIQUORICE_python4/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2897, in get_loc
    raise KeyError(key) from err
KeyError: 1

```

**Comment by peneder** [comment]
Hi,
That's odd - Thanks for not giving up :) 👍 

Not sure if that's the cause, but I'm noticing some warning messages prior to the error which are not expected. Seems like the seaborn is running in a newer version than expected. Have you installed LIQUORICE like so:
mamba create -n LIQUORICE -c bioconda -c conda-forge liquorice ?
Seaborn version should be 0.11.2 (see here: https://github.com/epigen/LIQUORICE/blob/68fa1b92d6a54f63c44812393cd78fbd0ac0b262/conda-recipe/meta.yaml)
It'd also be worth checking the pandas version (should be 1.1.4) and the matplotlib version (should be 3.1.1).

Alternatively, could you send me the "summary_across_samples_and_ROIS.csv" file? Then I could do some debugging on that. My email is peter.peneder@ccri.at.

best
Peter

**Comment by danarte** [comment]
Thanks again for the quick answer.
And that's a good catch on your part! not sure why or how my seaborn wasn't the correct version, but after reinstalling the whole environment with the command you provided, the summary was able to run correctly for all samples.

Thanks again, you are a true hero in the github arena!
